export interface ScaleInfo {
  name: string;
  notes: string[];
  root: string;
}

const SPANISH_ROOTS: Record<string, string> = {
  'do': 'C',
  're': 'D',
  'mi': 'E',
  'fa': 'F',
  'sol': 'G',
  'la': 'A',
  'si': 'B'
};

const NOTES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

/**
 * Procedurally translates and calculates notes for any major, minor, or pentatonic scale
 * generated by the AI in either Spanish or English format.
 */
export function getScaleData(scaleName: string): ScaleInfo {
  const defaultScale: ScaleInfo = {
    name: scaleName || 'Escala Desconocida',
    notes: [],
    root: ''
  };

  if (!scaleName) return defaultScale;

  const normalized = scaleName.toLowerCase().trim();

  // Match Spanish root name: do, re, mi, fa, sol, la, si with optional accidentals
  const rootRegex = /^(do|re|mi|fa|sol|la|si)(#|sostenido|b|bemol)?/i;
  const match = normalized.match(rootRegex);
  
  if (!match) {
    // Check for English root note: a-g with optional accidentals
    const englishRootRegex = /^([a-g])(#|sostenido|b|bemol)?/i;
    const engMatch = normalized.match(englishRootRegex);
    if (!engMatch) {
      return defaultScale;
    }
    
    let root = engMatch[1].toUpperCase();
    const accidental = engMatch[2];
    if (accidental === '#' || accidental === 'sostenido') {
      root += '#';
    } else if (accidental === 'b' || accidental === 'bemol') {
      root = normalizeFlat(root);
    }
    return buildScale(root, scaleName, normalized);
  }

  const spanishRoot = match[1];
  const accidental = match[2];
  let englishRoot = SPANISH_ROOTS[spanishRoot];

  if (accidental === '#' || accidental === 'sostenido') {
    englishRoot += '#';
  } else if (accidental === 'b' || accidental === 'bemol') {
    englishRoot = normalizeFlat(englishRoot);
  }

  return buildScale(englishRoot, scaleName, normalized);
}

/**
 * Normalizes flat note strings to their sharp chromatic counterparts.
 */
function normalizeFlat(root: string): string {
  switch (root) {
    case 'C': return 'B';
    case 'D': return 'C#';
    case 'E': return 'D#';
    case 'F': return 'E';
    case 'G': return 'F#';
    case 'A': return 'G#';
    case 'B': return 'A#';
    default: return root;
  }
}

/**
 * Builds the chromatic notes sequence for standard scale degrees.
 */
function buildScale(root: string, originalName: string, normalizedName: string): ScaleInfo {
  const rootIndex = NOTES.indexOf(root);
  if (rootIndex === -1) {
    return { name: originalName, notes: [], root };
  }

  let semitones: number[];
  
  // Detect pentatonic mode
  if (normalizedName.includes('pentatónica') || normalizedName.includes('pentatonica')) {
    if (normalizedName.includes('menor') || normalizedName.includes('minor') || normalizedName.includes('m')) {
      // Minor Pentatonic: 1, b3, 4, 5, b7
      semitones = [0, 3, 5, 7, 10];
    } else {
      // Major Pentatonic: 1, 2, 3, 5, 6
      semitones = [0, 2, 4, 7, 9];
    }
  } else {
    // Diatonic mode
    if (normalizedName.includes('menor') || normalizedName.includes('minor') || normalizedName.includes('m')) {
      // Natural Minor: 1, 2, b3, 4, 5, b6, b7
      semitones = [0, 2, 3, 5, 7, 8, 10];
    } else {
      // Major: 1, 2, 3, 4, 5, 6, 7
      semitones = [0, 2, 4, 5, 7, 9, 11];
    }
  }

  const scaleNotes = semitones.map(interval => NOTES[(rootIndex + interval) % 12]);

  return {
    name: originalName,
    notes: scaleNotes,
    root
  };
}
